title: Arthur Krasnomakov-Paukovsky
author:
  en: Arthur Krasnomakov-Paukovsky
  ru: Артур Красномаков-Пауковский
  nl: Artuurros Van Der Kalproos Van Spinneweb
description: |
  **Surrealism**. These works are to some extent inspired by the paintings of **Hieronymus Bosch**. And in essence they serve similar purposes - they show the **dark sides** and expose **negative qualities**. The same stories and miniatures, in which there is no darkness, although now they are a minority, simply create a surreal world.

  The genre, depictions of ordinary situations.

  To no lesser extent, one can detect the influence of **Mikhail Zoshchenko** in the desire to write about simple things, from the position of an accomplice to what is happening. From within something ordinary and insignificant, as it may seem at first glance.

  But in the context of creativity beyond the scope of this blog, the author follows the tradition of Russian and Ukrainian writers who wrote about the devil and similar phenomena in society. **Bulgakov**, **Gogol**, **Dostoevsky** with their **Diaboliad**, **Master and Margarita**, **Viy** and **Demons**. Which, in turn, organically intertwines with motives close to the Japanese surrealists.

  **Rethinking Russian classics**, mystical plots of religious literature. Hunter's notes became **Demon Hunter's notes**, peasant and domestic life were replaced by **cyberpunk setups** and **interspatial, timeless meta plots**.

  Why not just write about **God and Truth**? About science? The author asks himself these questions and answers them. He writes several layers of his thoughts, uses different forms of art. But works about Truth and God will not replace the sad and negative experience that **mistakes and aggression** carry.

  "**Vanity and Self-love** acquire more personalized forms in miniatures, and like **brain dance** convey a certain depth of the moment of the surreal world so that the reader can see what should not be." - This is the conclusion made by the writer. Overcoming the limitations of dialectics in himself, the author creates a format that, in his opinion, is capable of showing **dangerous and sharp angles and themes** of technological progress, modern life, history, the future, without his own personal opinion, but with a **positive intention**.

theme: minima 